### ISSUE TITLE
migration name add_coherence_to_user is duplicated

### ISSUE THREAD

**Issue by ronalson** [sliveapp/ItSlive#1]
There are two migrations file with the same name and this is causing erros when running `mix ecto.migrate`

**Comment by ronalson** [comment]
For now we can run the migrations one-by-one using `mix ecto.migrate --step 1`. However it's recommend to not have to migrations with the same name.

**Comment by luizfonseca** [comment]
This is weird, they have the same name (and they do different things), but not the same timestamps (which are used when running `ecto.migrate`. I will just rename them for future setups
